anthropic_api_key: "<YOUR_ANTHROPIC_API_KEY>"
model: "claude-3-haiku-20240307"
temp: 1.0
max_tokens: 150
api_enabled: True
tts_api_url: "https://www.tetyys.com/SAPI4/SAPI4"
tts_voice: "Adult Male #2, American English (TruVoice)"
tts_pitch: "140"
tts_speed: "157"
use_system_tts: True
